### PR TITLE
separate incoming/passed events and sort them differently

### PR DESCRIPTION
**Pull request by OlegZharkov**
resolves https://github.com/usegalaxy-eu/website/issues/629

This PR separates events between, current/future and passed. Also I sort them differently (as suggested by @tnabtaf), in ascending and descending order.
Please DO NOT merge this PR just yet. I would really appreciate your feedback and a few suggestions. 

Thanks to @tnabtaf and @bgruening for the proposal

A few screenshots, please try it out if you have a bit of spare time, thanks.

image
image

### CODE REVIEW

**Comment by beatrizserrano** [comment]
thanks, @OlegZharkov! Looking at it locally, what confuses me a bit is having 'Incoming' at the bottom of the green section and 'Passed' at the very bottom of the page. What about removing the 'Incoming' and having a header between the green and yellow sections saying 'Past events'?

**Comment by tnabtaf** [comment]
+1 to everything @beatrizserrano says.  (Ever!)  That was quick @OlegZharkov !

**Comment by OlegZharkov** [comment]
alright @beatrizserrano @tnabtaf 
what about now? Hopefully, it looks better
image
and 
image

**Comment by OlegZharkov** [comment]
another thing.... Should I also consider events that started but didn't finish just yet (for example, started on 5th of April, ends in May)? If yes, do I put them in incoming? should I also rename incoming to ''Current"?

Alternatively, I can also create another table "Current". Then I will show "Current" -> "Future/Incoming" -> "Passed"

**Comment by tnabtaf** [comment]
@OlegZharkov I lean towards "Current & Upcoming" and "Past" as labels.

Looks good.

Cheers

**Comment by beatrizserrano** [comment]
+1 to everything @tnabtaf says :)

@ OlegZharkov looks very nice locally, thanks! Will we also have it on the front page?

**Comment by OlegZharkov** [comment]
Ok then, if you like it, feel free to merge it.

> @ OlegZharkov looks very nice locally, thanks! Will we also have it on the front page?

what is your vision on the front page @beatrizserrano? it's only 6 events that fit within that box. Do you also want to squeeze past events in there?

**Comment by beatrizserrano** [comment]
no, only the closest 6 upcoming ones would work IMO

**Comment by OlegZharkov** [comment]
> no, only the closest 6 upcoming ones would work IMO

Ah, I see what you mean. You want to change the sorting direction. I will add it in another PR for that

**Comment by beatrizserrano** [comment]
cool, thanks a lot @OlegZharkov for the quick and nice fix!!

**Review by beatrizserrano — APPROVED** [review]

**Comment by bgruening** [comment]
Awesome! Thanks!

**Pull request merged**
