### PR TITLE
Add Materials subdomain

### PR DESCRIPTION
**Pull request by elichad**
Page a bit of a placeholder while we polish up our tools for the toolshed, but keen to get the subdomain started.

Is there anything else we need to do to get this set up?

### CODE REVIEW

**Comment by beatrizserrano** [comment]
Thanks @elichad :) If you like, we can also have it listed here: https://galaxyproject.org/community/#communities-of-practice

**Comment by elichad** [comment]
Yes please! Do I need to make a PR for that too?

**Comment by elichad** [comment]
Thanks, done!

**Comment by bgruening** [comment]
@elichad that looks great. The other steps are described here: https://github.com/usegalaxy-eu/operations/blob/master/subdomains.md

**Pull request merged**
