### PR TITLE
Delete 2019-04-13-tool-update.md

### PR DESCRIPTION
**Pull request by bgruening**
@erasche this does not work as expected I think.

What is written here as update is not an update. We have not updated that many tools.
And real updates, not upgrades, are not installed.

### CODE REVIEW

**Comment by erasche** [comment]
> What is written here as update is not an update. We have not updated that many tools

I'm just parsing the output of ephemeris, this is everything that was written in the log as

> repository gemini_actionable_mutations installed successfully (in 0:00:23.574517) at revision 3630a6e624d4

If that's not right then we need to fix ephemeris maybe?

**Comment by erasche** [comment]
I've disabled the automatic post adding until we identify a solution.

**Comment by bgruening** [comment]
Yes its a ephemeris and/or bioblend and/or TS issue.

**Comment by bgruening** [comment]
Eitherway, thats a super cool feature, thanks that you put that togehter.

**Pull request merged**
