### PR TITLE
Frontpage polishing

### PR DESCRIPTION
**Pull request by bagnacan**
- fixed link to tutorial _RNA-seq counts to genes_
- fixed link to dataset _RNA-seq counts to genes_
- removed link to not working interactive tour of tutorial _Network analysis with Heinz_
- added link to slides of tutorial _Visualization of RNA-Seq results with CummeRbund_
- fixed typo of tool entry _FastQC_

### CODE REVIEW

**Comment by erasche** [comment]
Can one of the admins verify this patch?

**Comment by bgruening** [comment]
@erasche can you please check the latest homepage, maybe clean your cache. For me Heinz Tour is working and also the tutorial links are working.

The link to the dataset is also working for, I'm confused :(

**Comment by bagnacan** [comment]
Ouch, I guess I was somehow looking at some cached version of the frontpage. I'm sorry abou that.

The only thing to still fix are:
- the typo on FastCQ, which is _FastQC!_ in the tools list
- the link to the dataset, which points [here](https://figshare.com/s/f5d63d8c265a05618137) (dataset of the tutorial _RNA-Seq reads to counts_) instead of [here](https://figshare.com/s/1d788fd384d33e913a2a) (dataset of the tutorial _RNA-Seq counts to genes_)

**Comment by bgruening** [comment]
Upps, that slipped through :(

**Comment by mblue9** [comment]
Thanks for fixing @bagnacan!

**Pull request merged**
