### PR TITLE
added de.NBI training announcement @ GMDS 2018

### PR DESCRIPTION
**Pull request by bagnacan**
Added the training announcement at GMDS 2018 (Osnabrück).
- since it's the GMDS organisation team that takes care of the registration procedures, I pointed the registration link to the GMDS webpage, instead of the de.NBI [announcement](http://www.denbi.de/22-training-cat/training-courses/599-rna-seq-data-analysis-with-galaxy-for-clinical-applications-gmds-2018)
- the `emed` supporter refers to the German [e:Med Systems Medicine Network](http://www.sys-med.de/en/)

### CODE REVIEW

**Comment by erasche** [comment]
Can one of the admins verify this patch?

**Comment by erasche** [comment]
Hi @bagnacan this looks good, thanks. Is the training event given in German or English? The GMDS page is german but the deNBI annoucement is in english. Our audience is probably more english speaking than german speaking, so unless the training is completely in german it might be better to link to deNBI (or both saying something like "see the appropriate websites: english, deutsch")

**Comment by bagnacan** [comment]
Hi @erasche! The training will be entirely in English. However, I guess that the registration page from the GMDS is in German because the vast majority of the workshop/talks will be in German. I will add a link to the English announcement on the de.NBI page as well

**Comment by bgruening** [comment]
cool thanks.

**Pull request merged**
