### PR TITLE
Add post for bcc training

### PR DESCRIPTION
**Pull request by simonbray**

### CODE REVIEW

**Comment by bgruening** [comment]
@mtekman can you please add something similar? Should we also add an event?

**Comment by bgruening** [comment]
Thanks @simonbray!

**Comment by mtekman** [comment]
> @mtekman can you please add something similar? Should we also add an event?

I will talk with @khanteymoori  about this on monday

**Comment by bgruening** [comment]
@mtekman this is BCC.

**Comment by mtekman** [comment]
oh sure, I'll do it now then

**Pull request merged**
