### PR TITLE
miracum workshop

### PR DESCRIPTION
**Pull request by bgruening**
@wm75 kannst du bitte das file anpassen, so dass es für Miracum passt.
Und bitte ein TIaaS anmelden.

### CODE REVIEW

**Comment by wm75** [comment]
No idea whether the airport information will be relevant for anybody.

**Comment by wm75** [comment]
I chose 14:00 as the start time because, at least, from Magdeburg you can make it to Freiburg by then if you take a train at 6 something in the morning.

**Comment by bgruening** [comment]
More important is if we can finish in time if we start at 14.00 :)

Thanks!

**Comment by bgruening** [comment]
More important is if we can finish in time if we start at 14.00 :)

Thanks!

**Pull request merged**
