### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by OlegZharkov**
otherwise, it's really unclear how to build it (at least, it was for me)

### CODE REVIEW

**Comment by simonbray** [comment]
Are you sure this is correct? It doesn't work for me, I run it from the base directory without any problems.

I agree it would be good to improve the installation/build instructions - I have this note if this helps at all:

```
sudo apt install software-properties-common
sudo apt-add-repository -y ppa:rael-gc/rvm
sudo apt update
sudo apt install rvm # now check 'Run command as login shell' in terminal preferences and restart
rvm autolibs disable # so we don't have to give sudo our rvm pw
rvm requirements # manually install these, was nothing for me
rvm install ruby
gem install bundler
cd Repos/website/
bundle install --path vendor/bundle
bundle exec jekyll serve --watch
```

**Comment by simonbray** [comment]
Oh I see there is a conda build system nowadays, nice.

**Comment by gmauro** [comment]
I don't think you need to cd into _data
I just do in this way:
```
cd version/usegalaxy-eu/website/
conda create -n website
conda install ruby==2.4.1 #the same version used by Jenkins
gem update --system
gem install bundler
bundler install --gemfile _data/Gemfile
bundle exec --gemfile _data/Gemfile jekyll build
```
that is what our Jenkins server does (+/-).

**Comment by OlegZharkov** [comment]
> I don't think you need to cd into _data
> I just do in this way:
> 
> ```
> cd version/usegalaxy-eu/website/
> conda create -n website
> conda install ruby==2.4.1 #the same version used by Jenkins
> gem update --system
> gem install bundler
> bundler install --gemfile _data/Gemfile
> bundle exec --gemfile _data/Gemfile jekyll build
> ```
> 
> that is what our Jenkins server does (+/-).

Yeah, because you're using ```--gemfile _data/Gemfile```
otherwise, I get 
```Could not locate Gemfile```

**Comment by bgruening** [comment]
@OlegZharkov and all others, please checkout the Makefile. `make install` and `make run`

**Comment by bgruening** [comment]
See: https://github.com/usegalaxy-eu/website/issues/442 :)

**Comment by OlegZharkov** [comment]
> make run

yeah. the best way, I guess

**Comment by OlegZharkov** [comment]
Then I guess, wrong docs are worse than no docs.

**Comment by OlegZharkov** [comment]
> Are you sure this is correct? It doesn't work for me, I run it from the base directory without any problems.
> 
> I agree it would be good to improve the installation/build instructions - I have this note if this helps at all:
> 
> ```
> sudo apt install software-properties-common
> sudo apt-add-repository -y ppa:rael-gc/rvm
> sudo apt update
> sudo apt install rvm # now check 'Run command as login shell' in terminal preferences and restart
> rvm autolibs disable # so we don't have to give sudo our rvm pw
> rvm requirements # manually install these, was nothing for me
> rvm install ruby
> gem install bundler
> cd Repos/website/
> bundle install --path vendor/bundle
> bundle exec jekyll serve --watch
> ```

I tried to reproduce, doesn't work on Ubuntu 18.08

**Comment by bgruening** [comment]
@OlegZharkov is the makefile thing working for you? If so you can add this....

**Comment by OlegZharkov** [comment]
> @OlegZharkov is the makefile thing working for you? If so you can add this....

`make` works, it's in docs. I just thougt, it might be a good idea to remove  
```console	
bundle install --path vendor/bundle	
bundle exec jekyll serve --watch	
```

**Comment by OlegZharkov** [comment]
thank you @beatrizserrano!

**Pull request merged**
