### PR TITLE
Update index-proteomics.md to display usegalaxy-eu Gitter information

### PR DESCRIPTION
**Pull request by jraysajulga**
Is it possible to enable the "open chat" widget/button available on usegalaxy.eu (in the lower right corner)?

### CODE REVIEW

**Comment by erasche** [comment]
Can one of the admins verify this patch?

**Comment by erasche** [comment]
Hi @jraysajulga, if you want to do that, just include the snippet from the bottom of this page

https://github.com/usegalaxy-eu/website/blame/master/galaxy/index.md

**Comment by jraysajulga** [comment]
> Hi @jraysajulga, if you want to do that, just include the snippet from the bottom of this page
> 
> https://github.com/usegalaxy-eu/website/blame/master/galaxy/index.md

Thank you! I added that to the page.

**Comment by jraysajulga** [comment]
How is this looking now?

**Comment by bgruening** [comment]
@jraysajulga no ;) you copy and paste did not work :) What are these numbers :)

I added it in this commit: https://github.com/usegalaxy-eu/website/commit/b236ce5da96ddb01b7c8800b7b95eb2180ddc8dd

Check out the website, it should work now.

**Pull request closed without merging**
