### PR TITLE
Zauberkugel

### PR DESCRIPTION
**Pull request by aurelienmoumbock**

### CODE REVIEW

**Comment by bgruening** [comment]
@aurelienmoumbock hey, thanks for updating this site.

Do you know how to test it locally? Any help needed?

**Comment by aurelienmoumbock** [comment]
No, I don't. @simonbray suggested I create this pull request and he will crosscheck.

**Comment by bgruening** [comment]
Ok! If you are curious, have a look here: https://github.com/usegalaxy-eu/website#building

Thanks @aurelienmoumbock

**Comment by aurelienmoumbock** [comment]
Thanks @bgruening

**Review by simonbray — APPROVED** [review]
Looks good to me - thanks @aurelienmoumbock

**Comment by bgruening** [comment]
@aurelienmoumbock if you like please write a small blog post announcing your workflow and describing it a little bit.

You only need to create a markdown file here: https://github.com/usegalaxy-eu/website/tree/master/_posts

**Comment by aurelienmoumbock** [comment]
@bgruening @simonbray thanks. At the moment, I'm generating a tutorial for this workflow. Would it be preferable to announce both the workflow and training material in a single blog post ?

**Comment by bgruening** [comment]
Sounds like a good plan! Depending on how long the tutorial will take you also good write two posts, one about the workflow now and later about the tutorial, as you prefer.

**Pull request merged**
