### PR TITLE
Nanopore: update text + png

### PR DESCRIPTION
**Pull request by willemdek11**
I updated the toolkit image to the most up-to-date and added the tools in the description.

### CODE REVIEW

**Comment by erasche** [comment]
Can one of the admins verify this patch?

**Comment by erasche** [comment]
Hi @willemdek11, could you add Miniasm to `_data/tools.yaml`? I think that's the only one that's missing

**Comment by willemdek11** [comment]
> 
> 
> Hi @willemdek11, could you add Miniasm to `_data/tools.yaml`? I think that's the only one that's missing

I've done that! Thanks I tried to find myself where the tools were defined, but couldn't find it.

**Comment by erasche** [comment]
Looks good!

**Pull request merged**
