### PR TITLE
Conda build system

### PR DESCRIPTION
**Pull request by bgruening**
This PR is migrating the build process to conda-only. Hopefully, it gets more stable. Moreover, this is a test for the bigger GTN website.

ping @bebatut 

Thanks to @sodre for all his cool conda packages.

### CODE REVIEW

**Comment by erasche** [comment]
Could you also update https://github.com/usegalaxy-eu/website/blob/master/.build.sh? currently the makefile is not used. If we really need to switch to conda I guess we need to rebuild the jenkins worker nodes, because they will not have room for how much space conda takes up :(

**Comment by bgruening** [comment]
Mh, we do not need to use conda if we are happy with the status quo.
The problem is the local build that do tend to work for some people but not all.

I would have expected that we already have some conda on it. Galaxy testing needs conda isn't it? Aren't we sharing build-bots with Galaxy these days?

If you are not a fan of it, lets just merge in the environment.yml file and keep telling people that they can use it.

**Comment by erasche** [comment]
>  The problem is the local build that do tend to work for some people but not all.

ah yeah this is always an issue :( 

> I would have expected that we already have some conda on it.

We don't currently use it, only python virtualenvs.

> Galaxy testing needs conda isn't it? Aren't we sharing build-bots with Galaxy these days?

We don't share the actual machines, we just run some for them and they maintain the software stack inside. Currently none of our jobs run galaxy tests thought that would make a lot of sense, to test our own `_europe` branches.

> If you are not a fan of it, lets just merge in the environment.yml file and keep telling people that they can use it.

fine for me, should probably migrate to conda eventually though :)

**Comment by bgruening** [comment]
Just as information, jekyll-4 is for this website 50% faster (14s --> 7s)

**Comment by bgruening** [comment]
Added Gemfiles back, the problem is that jekyll checks these Gemfiles ... so with Gemfiles the makefile is not working ... narf

**Comment by erasche** [comment]
gosh, annoying. Let's try moving the gemfile to a different folder then. Maybe `_data` is fine.

Then we can update `bundler install` to be `bundler install --gemfile _data/Gemfile`?

**Comment by bgruening** [comment]
@mtekman can you please try laster master and the Makefile.

Hopefully this will help you an your scary Box to get the website build. It has a make install command.

**Comment by mtekman** [comment]
@bgruening  Yes it runs! Thank you so much

**Pull request merged**
