### PR TITLE
Announce the MiModD suite of tools

### PR DESCRIPTION
**Pull request by wm75**
... as soon as they are installed.

I'll fill the linked workflow then, too.

### CODE REVIEW

**Comment by erasche** [comment]
Can one of the admins verify this patch?

**Comment by bgruening** [comment]
I will do and install the tools tm ... training was merged today already.

**Comment by wm75** [comment]
thanks @bgruening !

**Comment by erasche** [comment]
@bgruening is there any way we could work in a reference to that PR, showing the openness of the system?

**Comment by bgruening** [comment]
`work in`to what?

**Comment by erasche** [comment]
into this open pr / blog post about it. Not sure how, but it seems like a nice thing to mention? I dunno. Maybe not important, feel free to leave out.

**Comment by bgruening** [comment]
I guess we should do that as a new blog post referencing this one and the B3Africa one ...

**Comment by erasche** [comment]
Sure, that works too! Even better idea.

**Comment by wm75** [comment]
ok, MiModD tools are installed and the workflow runs smoothly.
I think this can be posted whenever you see fit to do so.

**Comment by bgruening** [comment]
@wm75 have you tested the training as well? Or the other way around can you stick the workflow into the training?

**Comment by wm75** [comment]
the workflow follows the training exactly so, yes, I tested the training. With sticking it into you mean adding that same workflow to the training material repo?

**Comment by bgruening** [comment]
> same workflow to the training material repo?

Yes.

**Comment by wm75** [comment]
Sure, I can do that. Probably only on Monday though.

**Comment by bgruening** [comment]
Danke Wolfgang!

**Pull request merged**
