### PR TITLE
Hyperlink DOIs against preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Same as https://github.com/galaxyproject/training-material/pull/793. Gotta catch them all ;-D

### CODE REVIEW

**Comment by erasche** [comment]
Can one of the admins verify this patch?

**Comment by bgruening** [comment]
pokeball

**Comment by bgruening** [comment]
Thanks @katrinleinweber! Let me know when you are nearby Freiburg at one point.

**Comment by katrinleinweber** [comment]
Will do, thanks! Possibly in May 2019.

**Comment by katrinleinweber** [comment]
@bgruening Alternatively, will you attend [DILS](https://events.tib.eu/dils2018/) in Hannover?

**Comment by bgruening** [comment]
No sorry, there are https://galaxyproject.org/events/2018-europe-dev/ :(
Will we ever manage? :(

**Comment by katrinleinweber** [comment]
Spring 2019 then. Around [EAHIL2019](https://eahil2019.net/).

**Comment by bgruening** [comment]
Sure! You can also stay for https://galaxyproject.org/events/gcc2019/ :)

**Comment by katrinleinweber** [comment]
In that case, summer 2019 then ;-D

**Comment by katrinleinweber** [comment]
Hi @bebatut & @bgruening! You seem to have [a leak somewhere](https://github.com/usegalaxy-eu/website/search?q=%22dx.doi%22&unscoped_q=%22dx.doi%22) ;-) Shall I send another PR such as this one, or do you first want to check where those old links are coming from?

**Comment by bgruening** [comment]
@katrinleinweber upps :) fixed in https://github.com/usegalaxy-eu/website/commit/b84497c76c810d97e8126caf069d655c08388643

Frohe Weihnachten!

**Comment by katrinleinweber** [comment]
Danke sehr :-) Ebenfalls, und alles Gute für 2019!

**Pull request merged**
