### PR TITLE
WIP: GDC integration

### PR DESCRIPTION
**Pull request by bgruening**
migrated from https://github.com/usegalaxy-eu/issues/pull/91/files

tool currently not working :(

ping @fabio-cumbo

### CODE REVIEW

**Comment by fabio-cumbo** [comment]
That's really weird, it seems that there is a problem with the address to come back to Galaxy.

It is: 
[https://test.galaxyproject.org/tool_runner?tool_id=toolshed.g2.bx.psu.edu/repos/fabio/gdcwebapp/data_source_gdcwebapp/1.0.0&key=20180417162344_3691616d-9a00-4c14-839d-e0714ea4a58a](https://test.galaxyproject.org/tool_runner?tool_id=toolshed.g2.bx.psu.edu/repos/fabio/gdcwebapp/data_source_gdcwebapp/1.0.0&key=20180417162344_3691616d-9a00-4c14-839d-e0714ea4a58a)

But it should be something like this: 
[https://test.galaxyproject.org/async/data_source_gdcwebapp?key=20180417162344_3691616d-9a00-4c14-839d-e0714ea4a58a](https://test.galaxyproject.org/async/data_source_gdcwebapp?key=20180417162344_3691616d-9a00-4c14-839d-e0714ea4a58a)

I will try to fix that.
Thanks @bgruening

**Comment by fabio-cumbo** [comment]
It is also interesting that clicking on the second link (in my previous post) will produce a new working job in Galaxy..
Could it represent a security issue?

**Comment by erasche** [comment]
it should be under an anonymous user though? That should be fine. Both usegalaxy.org and .eu allow anonymous users to execute some jobs. So if that automatically triggers a pull of data that sounds like it's functioning correctly.

**Comment by fabio-cumbo** [comment]
@bgruening, thanks to @erasche, I have tested the data source tool on a new Galaxy instance (the latest stable release 18.01) and it seems to work correctly.

**Comment by bgruening** [comment]
@fabio-cumbo it still does not work.
`objectstore, _call_method failed: get_filename on , kwargs: {}` This is probably due to our object-store configuration, but this is not uncommon :(

Can you also please write a post on our website that you have joined the team and what you are working on?

**Comment by fabio-cumbo** [comment]
@bgruening could you please send me the whole stack in which the error appears?
Just to figure out better why it throws an exception.

**Pull request closed without merging**
