### PR TITLE
Add highmem post!

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
I love my cookie monster ;) give us more job-cookies :)

**Comment by erasche** [comment]
What exactly is it supposed to represent? Maybe I'm missing some association you have with cookie monster, cookies, and job queueing?

**Comment by bgruening** [comment]
Its cute, hungry and funny ;) That's it :laughing:

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
