### PR TITLE
change matrix icon

### PR DESCRIPTION
**Pull request by OlegZharkov**
Show the different icon, using the same icon as gitter is a bit awkward. 

thanks @wm75 for the start

image

### CODE REVIEW

**Comment by wm75** [comment]
@gmauro just made the `@` work by quoting and, IMHO, that's a slightly better solution cause that way the correct matrix address appears in the yml.
It really looks a bit awkward if you have two times the same icon under a person's name, but I assume most people will replace the gitter link with the matrix one instead of having both on the page?

**Comment by gmauro** [comment]
`@` is part of the matrix username, I prefer to double-quote it https://github.com/usegalaxy-eu/website/blob/5d23b960a9faeb527e4ccc27695fb2e1b47aae88/_data/people.yml#L110

**Comment by OlegZharkov** [comment]
> @gmauro just made the `@` work by quoting and, IMHO, that's a slightly better solution cause that way the correct matrix address appears in the yml.

Yeah, fair enough. 
> It really looks a bit awkward if you have two times the same icon under a person's name, but I assume most people will replace the gitter link with the matrix one instead of having both on the page?

well, not everyone has element and AFAIK you cannot send private messages from gitter to element, you only can access public rooms. As you have seen, a lot of people are hesitant to use element, thus gitter is not going anywhere any time soon. So we'll be stuck with both for now.

**Comment by bgruening** [comment]
Please merge if you feel its good to go.

**Review by davelopez — APPROVED** [review]

**Pull request merged**
