### PR TITLE
Add blogpost for tool recommendation paper

### PR DESCRIPTION
**Pull request by anuprulez**
Add blogpost for tool recommendation paper

### CODE REVIEW

**Comment by beatrizserrano** [comment]
Thanks, @anuprulez! Could you add a nice figure here? Like fig 1 or 6 for instance?

**Comment by anuprulez** [comment]
@beatrizserrano I added a couple of GIFs showing how to use the tool recommendation system.

**Comment by anuprulez** [comment]
I added an image. ping @beatrizserrano

**Comment by beatrizserrano** [comment]
Those gifs look cool! Thanks a lot @anuprulez :)

**Review by beatrizserrano — APPROVED** [review]

**Pull request merged**
