### PR TITLE
add certification post

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@JanLeendertse can you maybe have a look?

**Comment by JanLeendertse** [comment]
You're working with Calibre? Or only a library provided by them.

**Comment by JanLeendertse** [comment]
Ist okay. Ich kann allerdings nicht schreiben oder mergen wegen fehlender Rechte.

**Comment by bgruening** [comment]
> You're working with Calibre? Or only a library provided by them.

Its an integration to reduce image size and page load times.

> Ist okay. Ich kann allerdings nicht schreiben oder mergen wegen fehlender Rechte.

You have now access. Do you want to change anything?

**Comment by JanLeendertse** [comment]
Not really. But you asked me to review the blog post.

**Comment by bgruening** [comment]
Merci! :)

**Pull request merged**
